version: '3.0'
services:
  mysql:
    image: "gcr.io/payment-gateway-221815/payment-gateway_db"
    logging:
      driver: "none"
    environment:
      - MYSQL_ROOT_PASSWORD=1q2w3e4r
  app:
    image: "gcr.io/payment-gateway-221815/payment-gateway"
    environment:
      - mysql__host=mysql
      - mysql__password=1q2w3e4r
    volumes:
      - ./docker-entry-scripts/app:/entrypoint.d
    ports:
      - "3030:3030"
  test:
    image: "mhart/alpine-node:11"
    environment:
      - mysql__host=mysql
      - listen_address=app
    volumes:
      - ./:/code
      - ./docker-entry-scripts/test:/entrypoint.d
    working_dir: "/code"
    command: "/bin/sh"
    entrypoint: "./docker-init.sh"
    command: "npm test"
